# -----------------------------------------------------------------------
# 1. MAIN PATHS AND ENVIRONMENT
# -----------------------------------------------------------------------
# Essential paths for the application to function
music_library_path: /Users/yourusername/Music/Music/Music Library.musiclibrary
apple_scripts_dir: /Users/yourusername/Path/To/AppleScripts
# Base directory for all generated files (logs, reports, caches, etc.)
# RECOMMENDATION: Consider using a local folder instead of iCloud Drive to avoid potential syncing delays or errors.
logs_base_dir: /Users/yourusername/Path/To/Logs

# Python specific settings
python_settings:
  prevent_bytecode: true # Set to true to prevent __pycache__ generation

# -----------------------------------------------------------------------
# 2. EXECUTION AND PERFORMANCE
# -----------------------------------------------------------------------
# Controls how the script runs and interacts with system resources

# AppleScript interaction settings
apple_script_concurrency: 2 # Max number of simultaneous AppleScript calls
applescript_timeout_seconds: 1800 # Timeout for AppleScript execution (30 min)

# General retry logic for potentially recoverable errors (e.g., AppleScript updates)
max_retries: 2 # Number of retry attempts for applicable operations
retry_delay_seconds: 1 # Base delay between retries

# In-memory cache settings (used by CacheService for temporary data like fetched tracks)
cache_ttl_seconds: 1800 # Default lifetime for in-memory cache items (30 min)
album_cache_sync_interval: 300 # Interval for syncing in-memory cache with disk (5 min)
# Incremental update settings
incremental_interval_minutes: 60 # Interval for incremental updates (1 hour)

# -----------------------------------------------------------------------
# 3. FEATURE TOGGLES AND SETTINGS
# -----------------------------------------------------------------------
# Enable/disable major features and configure specific behaviors

# Metadata cleaning settings
cleaning:
  remaster_keywords:
    - remaster
    - remastered
    - Re-recording
    - Redux
    - Expanded
    - Special Edition
    - Deluxe Edition
    - Anniversary Edition
