secret:
  ignored_matches:
    - match: af2ef2fcecfa45457adf67c77d6d2863226f2d7c50ef18b0226458c0c6ccd327
      name: Generic High Entropy Secret - Genres Autoupdater v2.0/my-config.yaml:l.124
version: 2
