# config.yaml
music_library_path: "/Users/romanborodavkin/Music/Music/Music Library.musiclibrary"
apple_scripts_dir: "/Users/romanborodavkin/Library/Mobile Documents/com~apple~CloudDocs/3. Git/Own/Apple Scripts"
log_file: "/Users/romanborodavkin/Music/Music/music_genre_updater.log"
csv_output_file: "/Users/romanborodavkin/Music/Music/track_list.csv"
changes_report_file: "/Users/romanborodavkin/Music/Music/changes_report.csv"
last_incremental_run_file: "/Users/romanborodavkin/Music/Music/last_incremental_run.log"
backup_dir: "/Users/romanborodavkin/Music/Music/Backup"
incremental_interval_minutes: 60
max_retries: 3
retry_delay_seconds: 2
test_artists: []
cleaning:
  remaster_keywords:
    - "remaster"
    - "remastered"
exceptions:
  track_cleaning:
    - artist: "Rabbit Junk"
      album: "Xenospheres"